name: number-guess
version: git
summary: number-guess
description: |
  python3 number guessing game

grade: devel
confinement: devmode

apps:
  number-guess:
    command: bin/number-guess

parts:
  number-guess:
    source: https://github.com/ul7r41337h4x0r/guessprogram
    source-type: git
    plugin: python
    python-version: python3

